// ─────────────────────────────────────────────────────────────────────────────
// Placeholder / fallback data used when Sanity content isn't yet set up.
// This makes the site look polished out of the box.
// ─────────────────────────────────────────────────────────────────────────────

import type {
  SiteSettings,
  HeroData,
  BioData,
  StatData,
  MeetResultData,
  GalleryItemData,
  PressEntryData,
} from './types'

export const placeholderSettings: SiteSettings = {
  siteTitle: 'Kaylee Daniel | UK Pole Vault',
  siteDescription:
    'University of Kentucky pole vaulter. Track & Field athlete, content creator, and NIL partner. Follow the journey.',
  socialLinks: {
    instagram: 'https://instagram.com',
    tiktok: 'https://tiktok.com',
    twitter: 'https://x.com',
  },
}

export const placeholderHero: HeroData = {
  firstName: 'Kaylee',
  lastName: 'Daniel',
  tagline: 'Pole Vault · University of Kentucky',
  subTagline: '2024–25 Season · Junior',
  ctaText: 'See My Stats',
  ctaLink: '#stats',
  accentStat: 'Top 50 Nationally',
}

export const placeholderBio: BioData = {
  headline: 'Built for Height',
  quote: '"The bar is just the beginning."',
  quickFacts: {
    hometown: 'Las Vegas, NV',
    year: 'Junior',
    major: 'Clinical Leadership Management',
    height: "5'8\"",
    yearsAtUK: '2 Years',
  },
}

export const placeholderStats: StatData[] = [
  {
    _id: 'stat-1',
    event: 'Pole Vault',
    mark: '4.00m',
    markImperial: "13'1.5\"",
    venue: 'NCAA Outdoor Championships, Eugene OR',
    date: '2024-06-05',
    isIndoor: false,
    isPrimary: true,
    displayOrder: 1,
    note: 'Outdoor PR · NCAA Qualifier',
  },
  {
    _id: 'stat-2',
    event: 'Pole Vault (Indoor)',
    mark: '3.95m',
    markImperial: "12'11.5\"",
    venue: 'SEC Indoor Championships, Fayetteville AR',
    date: '2025-02-22',
    isIndoor: true,
    isPrimary: false,
    displayOrder: 2,
    note: 'Indoor PR',
  },
  {
    _id: 'stat-3',
    event: 'Pole Vault',
    mark: '3.90m',
    markImperial: "12'9.5\"",
    venue: 'SEC Outdoor Championships, College Station TX',
    date: '2024-05-10',
    isIndoor: false,
    isPrimary: false,
    displayOrder: 3,
  },
]

export const placeholderMeetResults: MeetResultData[] = [
  {
    _id: 'meet-1',
    meetName: 'SEC Indoor Championships',
    date: '2025-02-22',
    location: 'Fayetteville, AR',
    event: 'Pole Vault',
    mark: '3.95m',
    place: 4,
    isIndoor: true,
    season: '2024-25-indoor',
    isHighlight: true,
    notes: 'Indoor PR',
  },
  {
    _id: 'meet-2',
    meetName: 'UK Opener',
    date: '2025-01-18',
    location: 'Lexington, KY',
    event: 'Pole Vault',
    mark: '3.80m',
    place: 1,
    isIndoor: true,
    season: '2024-25-indoor',
    isHighlight: false,
    notes: 'Season opener win',
  },
  {
    _id: 'meet-3',
    meetName: 'Millrose Games',
    date: '2025-02-08',
    location: 'New York, NY',
    event: 'Pole Vault',
    mark: '3.85m',
    place: 5,
    isIndoor: true,
    season: '2024-25-indoor',
    isHighlight: false,
  },
  {
    _id: 'meet-4',
    meetName: 'NCAA Outdoor Championships',
    date: '2024-06-05',
    location: 'Eugene, OR',
    event: 'Pole Vault',
    mark: '4.00m',
    place: 12,
    isIndoor: false,
    season: '2024-outdoor',
    isHighlight: true,
    notes: 'Outdoor PR — First NCAA qualifier',
  },
  {
    _id: 'meet-5',
    meetName: 'SEC Outdoor Championships',
    date: '2024-05-10',
    location: 'College Station, TX',
    event: 'Pole Vault',
    mark: '3.90m',
    place: 3,
    isIndoor: false,
    season: '2024-outdoor',
    isHighlight: false,
  },
  {
    _id: 'meet-6',
    meetName: 'Mt. SAC Relays',
    date: '2024-04-18',
    location: 'Walnut, CA',
    event: 'Pole Vault',
    mark: '3.85m',
    place: 7,
    isIndoor: false,
    season: '2024-outdoor',
    isHighlight: false,
  },
  {
    _id: 'meet-7',
    meetName: 'SEC Indoor Championships',
    date: '2024-02-24',
    location: 'Fayetteville, AR',
    event: 'Pole Vault',
    mark: '3.80m',
    place: 6,
    isIndoor: true,
    season: '2023-24-indoor',
    isHighlight: false,
  },
]

export const placeholderGallery: GalleryItemData[] = [
  {
    _id: 'gallery-1',
    title: 'NCAA Championships 2024 — Eugene, OR',
    type: 'photo',
    category: 'competition',
    date: '2024-06-05',
    isFeatured: true,
    displayOrder: 1,
  },
  {
    _id: 'gallery-2',
    title: 'Morning training at the UK Track Facility',
    type: 'photo',
    category: 'training',
    date: '2025-01-10',
    isFeatured: false,
    displayOrder: 2,
  },
  {
    _id: 'gallery-3',
    title: 'SEC Championship Day 2',
    type: 'photo',
    category: 'competition',
    date: '2025-02-22',
    isFeatured: false,
    displayOrder: 3,
  },
  {
    _id: 'gallery-4',
    title: 'Vault technique breakdown 🎵',
    type: 'tiktok',
    tiktokUrl: 'https://www.tiktok.com/@kayleekd/video/7349123456789',
    category: 'training',
    date: '2025-01-20',
    isFeatured: false,
    displayOrder: 4,
  },
  {
    _id: 'gallery-5',
    title: 'Day in my life — UK athlete edition',
    type: 'photo',
    category: 'lifestyle',
    date: '2025-02-01',
    isFeatured: false,
    displayOrder: 5,
  },
  {
    _id: 'gallery-6',
    title: 'Brand collab shoot — Athleta x UK',
    type: 'photo',
    category: 'nil',
    date: '2024-11-15',
    isFeatured: false,
    displayOrder: 6,
  },
]

export const placeholderPress: PressEntryData[] = [
  {
    _id: 'press-1',
    title: 'Kaylee Daniel Breaks UK Indoor Pole Vault Record at SEC Championships',
    type: 'press',
    publication: 'Kentucky Kernel',
    date: '2025-02-23',
    description:
      'Junior pole vaulter Kaylee Daniel set a new University of Kentucky indoor record with a clearance of 3.95m at the SEC Indoor Championships in Fayetteville.',
    url: 'https://kykernel.com',
    isFeatured: true,
    displayOrder: 1,
  },
  {
    _id: 'press-2',
    title: 'SEC Network Athlete Spotlight: Building Her Brand in the Bluegrass',
    type: 'interview',
    publication: 'SEC Network',
    date: '2025-01-14',
    description:
      'Kaylee sits down with the SEC Network to talk about her pole vault journey, life at UK, and how she\'s navigating the NIL era as a student-athlete.',
    url: 'https://secnetwork.com',
    isFeatured: true,
    displayOrder: 2,
  },
  {
    _id: 'press-3',
    title: 'NIL Partnership Announcement',
    type: 'partnership',
    publication: 'Athleta',
    date: '2024-11-01',
    description:
      'Proud to partner with Athleta as part of their collegiate athlete program. Representing athletes who compete on and off the track.',
    isFeatured: false,
    displayOrder: 3,
  },
  {
    _id: 'press-4',
    title: 'NCAA Qualifier: Daniels Earns First Trip to Eugene',
    type: 'press',
    publication: 'UK Athletics',
    date: '2024-05-25',
    description:
      'University of Kentucky pole vaulter Kaylee Daniel earned her first NCAA Outdoor Championship qualifier with a 4.00m clearance at the SEC Championships.',
    url: 'https://ukathletics.com',
    isFeatured: false,
    displayOrder: 4,
  },
  {
    _id: 'press-5',
    title: 'SEC Academic Honor Roll',
    type: 'award',
    publication: 'Southeastern Conference',
    date: '2024-08-01',
    description:
      'Recognized on the SEC Academic Honor Roll for excellence in the classroom and on the track — Clinical Leadership Management student and UK Honors College member competing at the Division I level.',
    isFeatured: false,
    displayOrder: 5,
  },
]
