// ─────────────────────────────────────────────────────────────────────────────
// Placeholder / fallback data used when Sanity content isn't yet set up.
// This makes the site look polished out of the box.
// ─────────────────────────────────────────────────────────────────────────────

import type {
  SiteSettings,
  HeroData,
  BioData,
  StatData,
  MeetResultData,
  GalleryItemData,
  PressEntryData,
} from './types'

export const placeholderSettings: SiteSettings = {
  siteTitle: 'Kaylee Daniel | UK Pole Vault',
  siteDescription:
    'University of Kentucky pole vaulter. Transfer from Houston. Track & Field athlete, content creator, and NIL partner. Follow the journey.',
  socialLinks: {
    instagram: 'https://instagram.com',
    tiktok: 'https://tiktok.com',
    twitter: 'https://x.com',
  },
}

export const placeholderHero: HeroData = {
  firstName: 'Kaylee',
  lastName: 'Daniel',
  tagline: 'Pole Vault · University of Kentucky',
  subTagline: '2025–26 Season · Sophomore',
  ctaText: 'See My Stats',
  ctaLink: '#stats',
  accentStat: '4.15m Indoor PR',
}

export const placeholderBio: BioData = {
  headline: 'Built for Height',
  quote: '"The bar is just the beginning."',
  quickFacts: {
    hometown: 'Las Vegas, NV',
    year: 'Sophomore',
    major: 'Clinical Leadership Management',
    height: "5'8\"",
    yearsAtUK: '1st Year at UK',
  },
}

export const placeholderStats: StatData[] = [
  {
    _id: 'stat-1',
    event: 'Pole Vault (Indoor)',
    mark: '4.15m',
    markImperial: "13'7.25\"",
    venue: 'Razorback Invitational, Fayetteville AR',
    date: '2026-01-31',
    isIndoor: true,
    isPrimary: true,
    displayOrder: 1,
    note: 'Indoor PR · Collegiate Personal Best',
  },
  {
    _id: 'stat-2',
    event: 'Pole Vault (Outdoor)',
    mark: '4.01m',
    markImperial: "13'1.75\"",
    venue: 'Texas A&M 44 Farms Team Invitational, College Station TX',
    date: '2025-04-12',
    isIndoor: false,
    isPrimary: false,
    displayOrder: 2,
    note: 'Outdoor PR',
  },
  {
    _id: 'stat-3',
    event: 'Pole Vault (Indoor)',
    mark: '3.95m',
    markImperial: "12'11.5\"",
    venue: 'Commodore Winter Challenge, Nashville TN',
    date: '2025-12-06',
    isIndoor: true,
    isPrimary: false,
    displayOrder: 3,
    note: 'First meet at UK',
  },
]

export const placeholderMeetResults: MeetResultData[] = [
  // ── 2025–26 Indoor (UK) ──────────────────────────────────────────────────
  {
    _id: 'meet-1',
    meetName: 'Razorback Invitational',
    date: '2026-01-31',
    location: 'Fayetteville, AR',
    event: 'Pole Vault',
    mark: '4.15m',
    place: 5,
    isIndoor: true,
    season: '2025-26-indoor',
    isHighlight: true,
    notes: 'Collegiate Indoor PR — 13\'7.25"',
  },
  {
    _id: 'meet-2',
    meetName: 'Crossroads of America Invitational',
    date: '2026-01-24',
    location: 'Indianapolis, IN',
    event: 'Pole Vault',
    mark: '3.87m',
    place: 9,
    isIndoor: true,
    season: '2025-26-indoor',
    isHighlight: false,
  },
  {
    _id: 'meet-3',
    meetName: 'Commodore Winter Challenge',
    date: '2025-12-06',
    location: 'Nashville, TN',
    event: 'Pole Vault',
    mark: '3.95m',
    place: 4,
    isIndoor: true,
    season: '2025-26-indoor',
    isHighlight: false,
    notes: 'UK season debut',
  },
  // ── 2024–25 Outdoor (Houston) ────────────────────────────────────────────
  {
    _id: 'meet-4',
    meetName: 'Texas A&M 44 Farms Team Invitational',
    date: '2025-04-12',
    location: 'College Station, TX',
    event: 'Pole Vault',
    mark: '4.01m',
    place: 5,
    isIndoor: false,
    season: '2024-25-outdoor',
    isHighlight: true,
    notes: 'Outdoor PR — 13\'1.75"',
  },
  {
    _id: 'meet-5',
    meetName: 'Texas Invitational',
    date: '2025-03-29',
    location: 'Austin, TX',
    event: 'Pole Vault',
    mark: '4.00m',
    place: 2,
    isIndoor: false,
    season: '2024-25-outdoor',
    isHighlight: false,
  },
  {
    _id: 'meet-6',
    meetName: 'Big 12 Outdoor Championships',
    date: '2025-05-15',
    location: 'Lubbock, TX',
    event: 'Pole Vault',
    mark: '3.76m',
    place: 18,
    isIndoor: false,
    season: '2024-25-outdoor',
    isHighlight: false,
  },
  // ── 2024–25 Indoor (Houston) ─────────────────────────────────────────────
  {
    _id: 'meet-7',
    meetName: 'Texas A&M Ted Nelson Invitational',
    date: '2025-01-25',
    location: 'College Station, TX',
    event: 'Pole Vault',
    mark: '3.93m',
    place: 3,
    isIndoor: true,
    season: '2024-25-indoor',
    isHighlight: false,
    notes: 'Houston indoor PR',
  },
  {
    _id: 'meet-8',
    meetName: 'Leonard Hilton Memorial Invitational',
    date: '2025-01-10',
    location: 'Houston, TX',
    event: 'Pole Vault',
    mark: '3.85m',
    place: 2,
    isIndoor: true,
    season: '2024-25-indoor',
    isHighlight: false,
    notes: 'Collegiate debut',
  },
  {
    _id: 'meet-9',
    meetName: 'Big 12 Indoor Championships',
    date: '2025-02-28',
    location: 'Lubbock, TX',
    event: 'Pole Vault',
    mark: '3.86m',
    place: 15,
    isIndoor: true,
    season: '2024-25-indoor',
    isHighlight: false,
  },
]

export const placeholderGallery: GalleryItemData[] = [
  {
    _id: 'gallery-1',
    title: 'Razorback Invitational 2026 — Fayetteville, AR',
    type: 'photo',
    category: 'competition',
    date: '2026-01-31',
    isFeatured: true,
    displayOrder: 1,
  },
  {
    _id: 'gallery-2',
    title: 'Morning training at the UK Track Facility',
    type: 'photo',
    category: 'training',
    date: '2025-12-01',
    isFeatured: false,
    displayOrder: 2,
  },
  {
    _id: 'gallery-3',
    title: 'Commodore Winter Challenge — Nashville',
    type: 'photo',
    category: 'competition',
    date: '2025-12-06',
    isFeatured: false,
    displayOrder: 3,
  },
  {
    _id: 'gallery-4',
    title: 'Vault technique breakdown 🎵',
    type: 'tiktok',
    tiktokUrl: 'https://www.tiktok.com/@kayleekd/video/7349123456789',
    category: 'training',
    date: '2025-11-20',
    isFeatured: false,
    displayOrder: 4,
  },
  {
    _id: 'gallery-5',
    title: 'Day in my life — UK athlete edition',
    type: 'photo',
    category: 'lifestyle',
    date: '2026-01-15',
    isFeatured: false,
    displayOrder: 5,
  },
  {
    _id: 'gallery-6',
    title: 'Liberty High School throwback',
    type: 'photo',
    category: 'lifestyle',
    date: '2024-06-01',
    isFeatured: false,
    displayOrder: 6,
  },
]

export const placeholderPress: PressEntryData[] = [
  {
    _id: 'press-1',
    title: 'Kaylee Daniel Sets Collegiate Indoor PR of 4.15m at Razorback Invitational',
    type: 'press',
    publication: 'UK Athletics',
    date: '2026-02-01',
    description:
      'Transfer pole vaulter Kaylee Daniel cleared 4.15m (13\'7.25") at the Razorback Invitational in Fayetteville, setting a new collegiate indoor personal best in her first SEC season at Kentucky.',
    url: 'https://ukathletics.com',
    isFeatured: true,
    displayOrder: 1,
  },
  {
    _id: 'press-2',
    title: 'Transfer Profile: Kaylee Daniel Brings Big 12 Experience to UK Vaulting',
    type: 'interview',
    publication: 'Kentucky Kernel',
    date: '2025-10-01',
    description:
      'Las Vegas native Kaylee Daniel talks about her transfer from Houston to Kentucky, the leap from the Big 12 to the SEC, and her goals for the 2025–26 season.',
    url: 'https://kykernel.com',
    isFeatured: true,
    displayOrder: 2,
  },
  {
    _id: 'press-3',
    title: 'NIL Partnership Announcement',
    type: 'partnership',
    publication: 'Brand Partner',
    date: '2025-09-01',
    description:
      'Excited to announce a new NIL partnership. Building my brand on and off the track — more details coming soon.',
    isFeatured: false,
    displayOrder: 3,
  },
  {
    _id: 'press-4',
    title: 'Daniel Posts Outdoor PR of 4.01m at Texas A&M Invitational',
    type: 'press',
    publication: 'Houston Athletics',
    date: '2025-04-13',
    description:
      'Freshman pole vaulter Kaylee Daniel cleared 4.01m (13\'1.75") at the Texas A&M 44 Farms Team Invitational, setting a new outdoor personal record in her debut collegiate season.',
    url: 'https://uhcougars.com',
    isFeatured: false,
    displayOrder: 4,
  },
  {
    _id: 'press-5',
    title: 'SEC Academic Honor Roll',
    type: 'award',
    publication: 'Southeastern Conference',
    date: '2026-01-01',
    description:
      'Recognized on the SEC Academic Honor Roll for excellence in the classroom and on the track — Clinical Leadership Management student and UK Honors College member competing at the Division I level.',
    isFeatured: false,
    displayOrder: 5,
  },
]
